// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.testCanBus;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon motorDriveLeftFront;
    public static CANTalon motorDriveLeftRear;
    public static CANTalon motorDriveRightFront;
    public static CANTalon motorDriveRightRear;
    public static RobotDrive motorDriveRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        motorDriveLeftFront = new CANTalon(3);
        LiveWindow.addActuator("MotorDrive", "LeftFront", motorDriveLeftFront);
        
        motorDriveLeftRear = new CANTalon(4);
        LiveWindow.addActuator("MotorDrive", "LeftRear", motorDriveLeftRear);
        
        motorDriveRightFront = new CANTalon(1);
        LiveWindow.addActuator("MotorDrive", "RightFront", motorDriveRightFront);
        
        motorDriveRightRear = new CANTalon(2);
        LiveWindow.addActuator("MotorDrive", "RightRear", motorDriveRightRear);
        
        motorDriveRobotDrive41 = new RobotDrive(motorDriveLeftFront, motorDriveLeftRear,
              motorDriveRightFront, motorDriveRightRear);
        
        motorDriveRobotDrive41.setSafetyEnabled(true);
        motorDriveRobotDrive41.setExpiration(0.1);
        motorDriveRobotDrive41.setSensitivity(0.5);
        motorDriveRobotDrive41.setMaxOutput(1.0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
